# Package-specific defaults here.
# Company-specific defaults in /etc/flox.toml.
# User-specific overrides in ~/.floxrc.

[npfs]

    npfs_mountpoint = "/nix/profiles"

[floxpkgs]

    gitBaseURL = "https://github.com/"
    organization = "flox"
